In [1]:
import os 
import sys
import numpy as np
from scipy.spatial.transform import Rotation as R 
import rospy 
import rospkg
import jupyros as jr

from std_msgs.msg import String, Header
from geometry_msgs.msg import PoseStamped, Pose, Point, Quaternion

In [2]:
# add catkin_ws context 
sys.path.append("/home/junting/franka_ws/devel/lib/python3.9/site-packages")

from src.lmp import *
from src.env.multimodal_env import MultiModalEnv
from src.configs.config import load_config

cfg_tabletop = load_config("perception_few_shot_gpt_3.5.yaml")



Failed to import pyassimp, see https://github.com/ros-planning/moveit/issues/86 for more info
Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


[nltk_data] Downloading package punkt to /home/junting/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/junting/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [3]:
########################################
# initialize environment
########################################
rospy.init_node('jupyter_multimodal', log_level=rospy.DEBUG)
# get package root path 
pkg_root = rospkg.RosPack().get_path('instruct_to_policy')

# setup environment
env = MultiModalEnv(cfg_tabletop)


[DEBUG] [1701957516.116330, 0.000000]: init_node, name[/jupyter_multimodal], pid[2597332]
[DEBUG] [1701957516.116937, 0.000000]: binding to 0.0.0.0 0
[DEBUG] [1701957516.117344, 0.000000]: bound to 0.0.0.0 33435
[DEBUG] [1701957516.117496, 0.000000]: connecting to chao-desktop 43343
[DEBUG] [1701957516.118189, 0.000000]: ... service URL is rosrpc://chao-desktop:33435
[DEBUG] [1701957516.118583, 0.000000]: [/jupyter_multimodal/get_loggers]: new Service instance
[DEBUG] [1701957516.119445, 5454.893000]: ... service URL is rosrpc://chao-desktop:33435
[DEBUG] [1701957516.120003, 5454.893000]: [/jupyter_multimodal/set_logger_level]: new Service instance
[DEBUG] [1701957516.158593, 5454.932000]: connecting to chao-desktop 43343
[DEBUG] [1701957516.159402, 5454.933000]: connecting to chao-desktop 43343
[DEBUG] [1701957516.160362, 5454.934000]: connecting to chao-desktop 57687
[INFO] [1701957516.161578, 5454.935000]: camera_left: Waiting for camera_left/color/camera_info...
[DEBUG] [1701957516

/home/junting/miniforge-pypy3/envs/ros_env/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


LANGUAGE BACKBONE USE GRADIENT CHECKPOINTING:  False


In [4]:
env.reset()

[DEBUG] [1701957527.541875, 5466.295000]: Transitioning to ACTIVE (from WAITING_FOR_GOAL_ACK, goal: /jupyter_multimodal-1-5466.295)
[DEBUG] [1701957527.575748, 5466.329000]: Transitioning to WAITING_FOR_RESULT (from ACTIVE, goal: /jupyter_multimodal-1-5466.295)
[DEBUG] [1701957527.577978, 5466.331000]: Transitioning to DONE (from WAITING_FOR_RESULT, goal: /jupyter_multimodal-1-5466.295)
[DEBUG] [1701957527.684861, 5466.438000]: connecting to ('chao-desktop', 43343)
[DEBUG] [1701957527.685981, 5466.439000]: connecting to ('chao-desktop', 43343)
[DEBUG] [1701957527.686880, 5466.440000]: connecting to ('chao-desktop', 43343)
[DEBUG] [1701957527.687809, 5466.441000]: connecting to chao-desktop 43343
[DEBUG] [1701957527.689047, 5466.442000]: connecting to chao-desktop 43343
[DEBUG] [1701957527.691583, 5466.443000]: connecting to chao-desktop 34045
[DEBUG] [1701957527.692745, 5466.444000]: connecting to chao-desktop 34045
[INFO] [1701957528.937402, 5467.647000]: Environment reset.


In [5]:
print(os.getcwd())

/home/junting/catkin_ws/src/llm-manipulation-bench/instruct_to_policy/scripts


In [6]:
env.detect_objects(object_list=["apple", "plate", "bowl"])

/home/junting/miniforge-pypy3/envs/ros_env/lib/python3.9/site-packages/transformers/modeling_utils.py:907: FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/home/junting/miniforge-pypy3/envs/ros_env/lib/python3.9/site-packages/torch/nn/functional.py:4070: UserWarning: nn.functional.upsample_bilinear is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample_bilinear is deprecated. Use nn.functional.interpolate instead.")


inference time per image: 1.7238458859792445
tensor([[851.1652, 536.1738, 901.7881, 590.0108]]) ['apple']
inference time per image: 0.4822529189987108
tensor([[1118.5205,  429.1591, 1327.5215,  542.5580]]) ['plate']
inference time per image: 0.48819605400785804
tensor([[ 874.4218,  591.7472, 1011.2419,  704.9487]]) ['bowl']
inference time per image: 0.4839708429935854
tensor([[866.5488, 414.8352, 909.0527, 459.0865]]) ['apple']
inference time per image: 0.4816374459769577
tensor([[ 720.1912,  529.7885, 1029.8835,  685.6276]]) ['plate']
inference time per image: 0.4746538649778813
tensor([[674.9188, 380.5370, 756.0240, 453.2359]]) ['bowl']
inference time per image: 0.4884587050182745
tensor([], size=(0, 4)) []
inference time per image: 0.48455235300934874
tensor([], size=(0, 4)) []
inference time per image: 0.4839773509884253
tensor([[1167.4608,  251.0338, 1257.0444,  341.5673]]) ['bowl']
[DEBUG] [1701957535.782465, 5474.470000]: connecting to chao-desktop 34045
Added object apple_0 to 

In [7]:
env.scene.visualize_3d_bboxes()
env.get_obj_name_list()

['apple_0', 'plate_0', 'bowl_0']

In [8]:
env.add_scene_objects_to_moveit()

[DEBUG] [1701957538.466100, 5477.153000]: connecting to chao-desktop 34045
Added object apple_0 to planning scene
[DEBUG] [1701957538.497279, 5477.184000]: connecting to chao-desktop 34045
Added object plate_0 to planning scene
[DEBUG] [1701957538.545757, 5477.233000]: connecting to chao-desktop 34045
Added object bowl_0 to planning scene


In [9]:
grasp_pose = env.parse_adaptive_shape_grasp_pose('apple_0')

[INFO] [1701957538.631406, 5477.313000]: Sending perception data to grasp detection service
[DEBUG] [1701957538.634861, 5477.321000]: connecting to chao-desktop 37135


In [10]:
env.planning_scene.get_known_object_names()

['apple_0', 'bowl_0', 'plate_0']

In [11]:
env.objects

{'apple_0': {}, 'plate_0': {}, 'bowl_0': {}}

In [12]:
env.open_gripper()
env.grasp(grasp_pose)


[DEBUG] [1701957541.134768, 5479.819000]: Transitioning to ACTIVE (from WAITING_FOR_GOAL_ACK, goal: /jupyter_multimodal-2-5479.818)
[DEBUG] [1701957541.170045, 5479.853000]: Transitioning to WAITING_FOR_RESULT (from ACTIVE, goal: /jupyter_multimodal-2-5479.818)
[DEBUG] [1701957541.171078, 5479.855000]: Transitioning to DONE (from WAITING_FOR_RESULT, goal: /jupyter_multimodal-2-5479.818)
[DEBUG] [1701957541.172121, 5479.856000]: Waiting for rviz to update


[WARN] [1701957542.225198, 5480.908000]: MoveitEnv: Could not plan cartesian_path to target pose 
position: 
  x: -0.27649660290796935
  y: -0.17286453834982995
  z: 1.1564431072901833
orientation: 
  x: 0.6993529206633681
  y: -0.6677615559119899
  z: 0.1843941981573167
  w: 0.17606469405174707.
 Plan accuracy: 0.6086956521739131


[DEBUG] [1701957552.459397, 5491.136000]: Transitioning to ACTIVE (from WAITING_FOR_GOAL_ACK, goal: /jupyter_multimodal-3-5491.133)
[DEBUG] [1701957552.494185, 5491.170000]: Transitioning to WAITING_FOR_RESULT (from ACTIVE, goal: /jupyter_multimodal-3-5491.133)
[DEBUG] [1701957552.494934, 5491.171000]: Transitioning to DONE (from WAITING_FOR_RESULT, goal: /jupyter_multimodal-3-5491.133)
[DEBUG] [1701957552.496824, 5491.172000]: connecting to chao-desktop 34045
[DEBUG] [1701957552.498550, 5491.175000]: Waiting for rviz to update


True

In [13]:
env.close_gripper()
env.attach_object('apple_0')

[DEBUG] [1701957555.048203, 5493.723000]: Transitioning to ACTIVE (from WAITING_FOR_GOAL_ACK, goal: /jupyter_multimodal-4-5493.722)
[DEBUG] [1701957555.550191, 5494.224000]: Transitioning to WAITING_FOR_RESULT (from ACTIVE, goal: /jupyter_multimodal-4-5493.722)
[DEBUG] [1701957555.551868, 5494.226000]: Transitioning to DONE (from WAITING_FOR_RESULT, goal: /jupyter_multimodal-4-5493.722)


True

In [14]:
place_pose = env.parse_place_pose('apple_0', 'plate_0')
env.move_to_pose(place_pose)
env.open_gripper()
env.detach_object('apple_0')

[DEBUG] [1701957555.593313, 5494.248000]: Waiting for rviz to update
